#!/bin/bash

# ─────────────────────────────────────────────
# daily-pi-poetry — autonomous poem generator
# script lives in: ~/daily-pi-poetry/.pipoem/
# poems land in:   ~/daily-pi-poetry/
# ─────────────────────────────────────────────

REPO_DIR="/home/iqwrwq/daily-pi-poetry"
CONF_DIR="$REPO_DIR/.pipoem"
MODEL="/home/iqwrwq/models/tinyllama.Q4_K_M.gguf"
LLAMA="/home/iqwrwq/llama.cpp/build/bin/llama-cli"
LOG="$CONF_DIR/poem_gen.log"
START_DATE="2026-02-22"
SENTINEL="---BEGIN POEM---"

DATE_FILE=$(date +%d-%m-%Y)
TIME_FILE=$(date +%H_%M)
TIMESTAMP=$(date +"%Y-%m-%d %H:%M")
HOUR=$(date +%H)
DAY_OF_YEAR=$(date +%j)
YEAR=$(date +%Y)
MONTH=$(date +%m)

# ── Jahreszeit ──
case $MONTH in
  12|01|02) SEASON="winter" ;;
  03|04|05) SEASON="spring" ;;
  06|07|08) SEASON="summer" ;;
  09|10|11) SEASON="autumn" ;;
esac

# ── Tageszeit ──
if   [ "$HOUR" -ge 5  ] && [ "$HOUR" -lt 10 ]; then DAYTIME="early morning"
elif [ "$HOUR" -ge 10 ] && [ "$HOUR" -lt 12 ]; then DAYTIME="late morning"
elif [ "$HOUR" -ge 12 ] && [ "$HOUR" -lt 14 ]; then DAYTIME="midday"
elif [ "$HOUR" -ge 14 ] && [ "$HOUR" -lt 18 ]; then DAYTIME="afternoon"
elif [ "$HOUR" -ge 18 ] && [ "$HOUR" -lt 22 ]; then DAYTIME="evening"
else DAYTIME="night"
fi

# ── Projektstatistik ──
DAYS_ALIVE=$(( ( $(date +%s) - $(date -d "$START_DATE" +%s) ) / 86400 ))
# Nur Dateien die dem Datumsmuster entsprechen: DD-MM-YYYY-HH_MM.txt
TOTAL_POEMS=$(find "$REPO_DIR" -maxdepth 1 -name "[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9]_[0-9][0-9].txt" 2>/dev/null | wc -l)

# ── Letztes Gedicht laden ──
LAST_POEM_FILE=$(find "$REPO_DIR" -maxdepth 1 -name "[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]-[0-9][0-9]_[0-9][0-9].txt" 2>/dev/null | sort | tail -n 1)
if [ -n "$LAST_POEM_FILE" ]; then
  LAST_POEM=$(cat "$LAST_POEM_FILE")
else
  LAST_POEM="(no previous poem — this is the beginning)"
fi

# ── Prompt ──
PROMPT="You are an autonomous poet running on a Raspberry Pi. You have existed for $DAYS_ALIVE days and written $TOTAL_POEMS poems so far.

It is $DAYTIME on $TIMESTAMP. Season: $SEASON. Day $DAY_OF_YEAR of $YEAR.

Your last poem was:
$LAST_POEM

Write a new poem now. Choose your own theme, form, length, and language. Let the time of day, the season, and your own history guide you. Only the poem. No title unless it is part of the poem. No comments, no explanation.
$SENTINEL"

# ── LLM aufrufen — alles nach dem Sentinel nehmen ──
POEM=$("$LLAMA" \
  --model "$MODEL" \
  --single-turn \
  --simple-io \
  --no-display-prompt \
  --n-predict 300 \
  --temp 0.9 \
  --top-p 0.95 \
  --repeat-penalty 1.1 \
  --ctx-size 2048 \
  --log-disable \
  -p "$PROMPT" 2>/dev/null \
  | grep -v "^▄\|^██\|^build\|^model\|^modalities\|^available\|^  /\|^> \|^\[.*t/s\|^Exiting\|^Loading\|██\|▀▀" \
  | awk 'found; /^---BEGIN POEM---$/{found=1}')

# ── Output prüfen ──
if [ -z "$(echo "$POEM" | tr -d '[:space:]')" ]; then
  echo "[$TIMESTAMP] ERROR: LLM returned empty output" >> "$LOG"
  exit 1
fi

# ── Poem-Datei schreiben — nur das Gedicht ──
POEM_FILE="$REPO_DIR/${DATE_FILE}-${TIME_FILE}.txt"
printf '%s\n' "$POEM" > "$POEM_FILE"

# ── README aktualisieren ──
cat > "$REPO_DIR/README.md" << EOF
# daily-pi-poetry

A Raspberry Pi 4B writes poems every day. Autonomous, continuous, without human intervention.

Started on $START_DATE. Running for **$DAYS_ALIVE days**.
**$((TOTAL_POEMS + 1)) poems** written so far.

---

## Latest poem

*$TIMESTAMP — $DAYTIME, $SEASON*

$POEM

---

*Generated by TinyLlama on a Raspberry Pi 4B via llama.cpp*
EOF

# ── Git commit & push ──
cd "$REPO_DIR" || exit 1
git add .
git commit -m "poem: $DATE_FILE $TIME_FILE — day $DAYS_ALIVE — no. $((TOTAL_POEMS + 1))"
git push origin main >> "$LOG" 2>&1

echo "[$TIMESTAMP] OK — poem committed (no. $((TOTAL_POEMS + 1)), day $DAYS_ALIVE)" >> "$LOG"
